name: mocness-extraction
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python>=3.8
  - pytorch>=2.0
  - torchvision
  - pip
  - pillow>=10.0
  - opencv
  - pytesseract
  - protobuf
  - sentencepiece
  - pip:
    - transformers>=4.20.0
    - datasets>=4.0.0
    - python-dotenv>=1.0.0
    - huggingface-hub
    - layoutparser[layoutmodels,tesseract]
    - detectron2
